# Generated by Django 4.2.2 on 2023-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0002_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
