# Generated by Django 4.2.2 on 2023-06-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0003_post"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
