# Generated by Django 4.2.2 on 2023-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0004_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
