# Generated by Django 4.2.2 on 2023-06-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0005_user_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="holiday_info",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
